### ISSUE TITLE
Error when using openSesame

### ISSUE THREAD

**Issue by ynren1020** [zwdzwd/sesame#33] opened 2021-05-03 15:54 UTC
Hi, 

I installed sesame on my mac laptop by using command BiocManager::install("sesame").
And then when I run openSesame(idat_dir), it gave me an error message like below:

Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"

I found some others reported similar error message when using "AnnotationHub", so I followed a similar solution to downgrade dplyr to 0.8.2 and dbplyr 1.3.0, it does not work either.
I installed ExperimentHub by BiocManager::install("ExperimentHub",version = "3.10"). It still does not work.

Do you know how I could solve this problem?

Thank you so much!

Yanan

**Comment by zwdzwd** [comment] 2021-05-03 17:49
can you show me your `sessionInfo()`? sounds like this is an ExperimentHub / AnnotationHub error?

**Comment by zwdzwd** [comment] 2021-05-03 17:55
Sounds like you just need to "Update your R / Bioconductor installation to R version 4.0.3 and Bioconductor version 3.12."

based on
https://support.bioconductor.org/p/p132709/
?

**Comment by ynren1020** [comment] 2021-05-03 17:55
Thanks a lot, Wanding! Here is my session info:


R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:
/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK:
/Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
base

other attached packages:
[1] sesame_1.4.0         sesameData_1.4.0     ExperimentHub_1.12.0
AnnotationHub_2.18.0
[5] BiocFileCache_1.10.2 dbplyr_2.1.1         BiocGenerics_0.32.0

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.1              BiocVersion_3.10.1
 [3] purrr_0.3.4                   DNAcopy_1.60.0
 [5] colorspace_2.0-0              vctrs_0.3.8
 [7] generics_0.1.0                htmltools_0.5.1.1
 [9] stats4_3.6.1                  yaml_2.2.1
[11] utf8_1.2.1                    interactiveDisplayBase_1.24.0
[13] blob_1.2.1                    rlang_0.4.11
[15] pillar_1.6.0                  later_1.2.0
[17] glue_1.4.2                    DBI_1.1.1
[19] BiocParallel_1.20.1           rappdirs_0.3.3
[21] RColorBrewer_1.1-2            bit64_4.0.5
[23] matrixStats_0.58.0            lifecycle_1.0.0
[25] wheatmap_0.1.0                memoise_2.0.0
[27] Biobase_2.46.0                IRanges_2.20.2
[29] fastmap_1.1.0                 httpuv_1.6.0
[31] curl_4.3.1                    fansi_0.4.2
[33] AnnotationDbi_1.48.0          illuminaio_0.28.0
[35] preprocessCore_1.48.0         Rcpp_1.0.6
[37] xtable_1.8-4                  openssl_1.4.4
[39] promises_1.2.0.1              BiocManager_1.30.12
[41] cachem_1.0.4                  base64_2.0
[43] S4Vectors_0.24.4              mime_0.10
[45] bit_4.0.4                     askpass_1.1
[47] digest_0.6.27                 dplyr_1.0.5
[49] shiny_1.6.0                   grid_3.6.1
[51] tools_3.6.1                   magrittr_2.0.1
[53] tibble_3.1.1                  RSQLite_2.2.7
[55] randomForest_4.6-14           crayon_1.4.1
[57] pkgconfig_2.0.3               ellipsis_0.3.2
[59] assertthat_0.2.1              httr_1.4.2
[61] rstudioapi_0.13               R6_2.5.0
[63] compiler_3.6.1

Yanan Ren, Ph.D., M.S.
Biostatistician
The Hormel Institute
University of Minnesota
801 16TH AVE NE,
Austin, MN, 55912
***@***.*** | 770-688-0446

**Comment by ynren1020** [comment] 2021-05-03 18:00
Thank you, Wanding! I am working on it now!

Best,

Yanan

Yanan Ren, Ph.D., M.S.
Biostatistician
The Hormel Institute
University of Minnesota
801 16TH AVE NE,
Austin, MN, 55912
***@***.*** | 770-688-0446

**Comment by ynren1020** [comment] 2021-05-04 21:00
Dear Wanding,

After updating R to 4.0 and bioconductor to 3.12, the issue was resolved. I
have another question related to batch effect. I have two batch samples
processed at different times using EPIC platform (6 months apart), I am
wondering after using openSesame for these two batch samples, do I still
need to do a batch correction before pooling them together to do downstream
analysis? I saw you have mentioned that Sesame pipeline can relieviate the
batch effect in the Sesame paper. I am guessing the batch effect is already
removed in the process?

Thank you so much for your answer!

Yanan

Yanan Ren, Ph.D., M.S.
Biostatistician
The Hormel Institute
University of Minnesota
801 16TH AVE NE,
Austin, MN, 55912
***@***.*** | 770-688-0446

**Comment by zwdzwd** [comment] 2021-05-05 15:22
I am glad the problem is resolved.

Re batch effect: I don't think one can completely remove batch effect without harming the biological signal. As you mention, we do observe less batch effect after sesame data preprocessing. There might still be residual dependence of data on batch ID. My suggestion to this is always model batch ID explicitly. We can chat more offline or on a separate note for more detail. 

I will close this thread but you can still follow up if you have related issues.

Thanks,

**Closed by zwdzwd** 2021-05-05 15:22 UTC
